// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSusChef.Api.Data;

#nullable disable

namespace SmartSusChef.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126074726_AddStoreTable")]
    partial class AddStoreTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CarbonFootprint")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CarbonFootprint = 1.1m,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7582),
                            Name = "Tomato",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7598)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CarbonFootprint = 13.5m,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7601),
                            Name = "Cheese",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7601)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CarbonFootprint = 0.9m,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7604),
                            Name = "Dough",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7604)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CarbonFootprint = 0.5m,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7606),
                            Name = "Lettuce",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7607)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CarbonFootprint = 27.0m,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7698),
                            Name = "Beef",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7698)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7754),
                            Name = "Margherita Pizza",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7756)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7758),
                            Name = "Beef Burger",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(7758)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IngredientId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 0.3m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IngredientId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 0.15m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            IngredientId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IngredientId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RecipeId");

                    b.ToTable("SalesData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OpeningDate");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 83, DateTimeKind.Utc).AddTicks(9455),
                            Name = "Administrator",
                            PasswordHash = "$2a$11$MCPwavHuml54EKfVTg.1/.v9X2PxHjazKeXUxJNCkvG9MHn7ruY3O",
                            Role = "Manager",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 83, DateTimeKind.Utc).AddTicks(9464),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(6852),
                            Name = "Employee User",
                            PasswordHash = "$2a$11$O1DV9ldt8eHRHngnI8tD4OrRUo1S7o6KZzyjltx4ICNKB84HZwr6y",
                            Role = "Employee",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 47, 26, 230, DateTimeKind.Utc).AddTicks(6859),
                            Username = "employee"
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("IngredientId");

                    b.ToTable("WastageData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("SalesRecords")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("WastageRecords")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("WastageRecords");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("SalesRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
