// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSusChef.Api.Data;

#nullable disable

namespace SmartSusChef.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CarbonFootprint")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CarbonFootprint = 1.1m,
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(2996),
                            Name = "Tomato",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3015)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CarbonFootprint = 13.5m,
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3018),
                            Name = "Cheese",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3019)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CarbonFootprint = 0.9m,
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3022),
                            Name = "Dough",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3022)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CarbonFootprint = 0.5m,
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3025),
                            Name = "Lettuce",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3025)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CarbonFootprint = 27.0m,
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3028),
                            Name = "Beef",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3028)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3086),
                            Name = "Margherita Pizza",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3088)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3090),
                            Name = "Beef Burger",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(3091)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83ce1726-1dfa-4822-b3f4-0989b1c8419c"),
                            IngredientId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 0.3m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("c74430e7-b008-46e9-b9ed-8bea4390e06e"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("5e01e35c-571d-486f-8804-31028ea9a5db"),
                            IngredientId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 0.15m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("dce5c65b-400b-4627-bcdb-8b6f41dba4cd"),
                            IngredientId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("37d4cf70-a55c-4ac9-92d4-138d8c3f9810"),
                            IngredientId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("9e81d73e-1c73-4337-8020-dd71dc7966d6"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RecipeId");

                    b.ToTable("SalesData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 208, DateTimeKind.Utc).AddTicks(7825),
                            Name = "Administrator",
                            PasswordHash = "$2a$11$pbgI3k5CaqI.2cK90xdVA.xzIdHlV1rlQlhsAdUalddbcRQsoISTy",
                            Role = "Manager",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 208, DateTimeKind.Utc).AddTicks(7833),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(2167),
                            Name = "Employee User",
                            PasswordHash = "$2a$11$OxYACAQvLTSi63.SAYYIGuJIRxqvD28TMLTDzb71u2IpGjFHAYze2",
                            Role = "Employee",
                            UpdatedAt = new DateTime(2026, 1, 22, 7, 13, 49, 366, DateTimeKind.Utc).AddTicks(2173),
                            Username = "employee"
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("IngredientId");

                    b.ToTable("WastageData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("SalesRecords")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("WastageRecords")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("WastageRecords");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("SalesRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
